swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: '<script>alert(document.domain)</script>'
  termsOfService: "javascript:alert(document.cookie)"
  contact: 
    name: "API Support",
    url: "javascript:alert(document.cookie)",
    email: "javascript:alert(document.cookie)"
paths:
  /:
    get:
      responses:
        '200':
          description: Echo GET
